name: spendsmart
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  hive: ^2.2.3
  hive_flutter:
  freezed_annotation: ^2.4.3
  json_annotation: ^4.9.0
  logger:
  path_provider:
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_animate: ^4.5.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  hive_generator:
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
  - family: ArchitypeRenner
    fonts:
    - asset: assets/fonts/ArchitypeRenner-Bold.ttf
      weight: 700
    - asset: assets/fonts/ArchitypeRenner-Demi.ttf
      weight: 600
    - asset: assets/fonts/ArchitypeRenner-Medium.ttf
      weight: 500
    - asset: assets/fonts/ArchitypeRenner-Regular.ttf
      weight: 400

